# Generated by Django 4.1 on 2022-08-19 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_permission_role_userrole_rolepermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='id',
            field=models.CharField(default='d08cdece-07cb-4554-aedc-01966bc16db3', editable=False, max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.CharField(default='87af3e4e-5905-487c-9635-7f44119a8bff', editable=False, max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='id',
            field=models.CharField(default='af1033ce-7d9b-4a89-a6df-b801adc99dac', editable=False, max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='5a98065b-8119-443c-8a2c-f379d1145b2f', editable=False, max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='id',
            field=models.CharField(default='0e1dfb1d-f4da-4287-aafc-529bf7451717', editable=False, max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
