# Generated by Django 4.1 on 2022-08-19 19:57

from django.db import migrations


class Migration(migrations.Migration):
    def load_initial_data(apps, schema_editor):
        # get our model
        # get_model(appname, modelname)
        model = apps.get_model('authentication', 'permission')
        model.objects.create(
        id='37cd5041-c78e-495d-b810-558fa9c8017a', description='create_permission')

        model.objects.create(
            id='658e2c1a-b590-42c7-9513-7804f8c51396', description='view_user')
        model.objects.create(id='4da86518-425a-4ece-84b3-fcfd50775322',
                             description='delete_activity')
        model.objects.create(id='c221027a-034b-4ea9-9cf4-27a8b1bae1d0',
                             description='view_project_reports')
        model.objects.create(id='35cd26ff-7482-433f-a893-0b3d6917de36',
                             description='delete_permission')
        model.objects.create(id='5ffb4666-7920-4620-99e9-ba5a76c4e990',
                             description='view_all_reports')
        model.objects.create(id='00de2da7-059e-4455-aaa8-dbdd3cd28cd6',
                             description='update_user_role')
        model.objects.create(id='a674ddf7-083f-41f1-a913-5bf08fe2578b',
                             description='delete_user_role')
        model.objects.create(id='13b3f932-917b-4e41-9dac-adadeba5db5e',
                             description='update_project')
        model.objects.create(id='9625b6d8-ae36-4287-8e39-4596d6ae96ad',
                             description='update_permission')
        model.objects.create(id='7aa09a7f-68a6-4ca6-b6a4-41a94cdb9095',
                             description='create_role_permission')
        model.objects.create(id='3af40ab1-7771-4851-a407-a2b9e53c0cb8',
                             description='create_user_role')
        model.objects.create(
            id='9c5e2a75-203b-4b14-9c9d-781b27464375', description='view_activity')
        model.objects.create(
            id='3d8012ca-19d1-454e-86e1-de22a1cc8db1', description='update_role')
        model.objects.create(
            id='044e8367-8729-438a-bec4-16f8a2cbfa6e', description='view_project')
        model.objects.create(id='db26e13d-a0e1-448e-b75c-7d444d4cc016',
                             description='view_permission')
        model.objects.create(
            id='fc40143f-c617-49cf-b83d-a8c3b0c7f1aa', description='update_user')
        model.objects.create(id='ada774f6-dc22-492b-9282-fa56af44549e',
                             description='update_activity')
        model.objects.create(id='1fb92058-fe84-4689-b629-e86ba0474c3f',
                             description='update_role_permission')
        model.objects.create(id='35633705-812c-4d7e-97a4-d98896bef48f',
                             description='view_role_permission')
        model.objects.create(id='b8cbf78e-9169-4f01-9c66-90bead34420d',
                             description='view_user_reports')
        model.objects.create(
            id='815a268a-c14d-4455-bba2-625ce707a6e2', description='delete_role')
        model.objects.create(
            id='1091c1b1-c0aa-45c8-8711-f275da6fc15c', description='delete_user')
        model.objects.create(id='75a54674-638d-4ef6-ab48-c26f0f1c3fdf',
                             description='delete_project')
        model.objects.create(id='d54df0de-85cd-4d92-8f8b-97d5aade1f8d',
                             description='view_user_role')
        model.objects.create(id='5acfd868-89ea-48d0-911b-ba4e8ea1624c',
                             description='create_project')
        model.objects.create(id='378fe6eb-6c50-4b06-b49e-55e6a3a6224b',
                             description='create_activity')
        model.objects.create(
            id='8d517df5-4784-4b16-8269-e138236c7d26', description='create_role')
        model.objects.create(
            id='4fa783ad-527f-4d60-9167-19a6733c8eb9', description='view_role')
        model.objects.create(id='ccd87130-76b2-4b4a-b5cb-4c128b2adff0',
                             description='delete_role_permission')
        model.objects.create(
            id='443c5932-2bde-484e-ac0a-b1c4923b6894', description='create_user')

    dependencies = [
        ('authentication', '0004_auto_20220819_1952'),
    ]

    operations = [
        migrations.RunPython(load_initial_data),
    ]
