# Generated by Django 4.1 on 2022-08-19 20:02

from django.db import migrations


class Migration(migrations.Migration):
    def load_initial_data(apps, schema_editor):
        model = apps.get_model('authentication', 'rolepermission')
        model.objects.create(id='098a4bc9-08b9-4cde-b8bf-a051c95e49c3',
                             role_id='9db782df-6704-458a-8bcd-426103e7808d', permission_id='00de2da7-059e-4455-aaa8-dbdd3cd28cd6')

        model.objects.create(id='95ec3de5-8612-4305-86e5-be0f963afe95',
                             role_id='9db782df-6704-458a-8bcd-426103e7808d', permission_id='044e8367-8729-438a-bec4-16f8a2cbfa6e')

        model.objects.create(id='8c3676f6-6ff6-4b89-8180-e6454c6503af',
                             role_id='9db782df-6704-458a-8bcd-426103e7808d', permission_id='1091c1b1-c0aa-45c8-8711-f275da6fc15c')

        model.objects.create(id='223132a2-8c4f-4a3c-9826-bc567e062b08',
                             role_id='9db782df-6704-458a-8bcd-426103e7808d', permission_id='13b3f932-917b-4e41-9dac-adadeba5db5e')

        model.objects.create(id='e4357c26-2f69-4aec-87cf-fb358e10e341',
                             role_id='9db782df-6704-458a-8bcd-426103e7808d', permission_id='1fb92058-fe84-4689-b629-e86ba0474c3f')

        model.objects.create(id='b2c2d9ef-36c6-44a9-9681-6866f964424d',
                             role_id='9db782df-6704-458a-8bcd-426103e7808d', permission_id='35633705-812c-4d7e-97a4-d98896bef48f')

        model.objects.create(id='04fbf9dd-126e-4959-9e1e-b551f1853e53',
                             role_id='9db782df-6704-458a-8bcd-426103e7808d', permission_id='35cd26ff-7482-433f-a893-0b3d6917de36')

        model.objects.create(id='795dd4a3-383c-4917-acc7-e9476ce6531b',
                             role_id='9db782df-6704-458a-8bcd-426103e7808d', permission_id='378fe6eb-6c50-4b06-b49e-55e6a3a6224b')

        model.objects.create(id='d518e2df-82eb-4a54-88ec-ed8dd261d12e',
                             role_id='9db782df-6704-458a-8bcd-426103e7808d', permission_id='37cd5041-c78e-495d-b810-558fa9c8017a')

        model.objects.create(id='2e619129-35f1-4f9d-815c-cc456f46c323',
                             role_id='9db782df-6704-458a-8bcd-426103e7808d', permission_id='3af40ab1-7771-4851-a407-a2b9e53c0cb8')

        model.objects.create(id='e6a49ec6-6199-49a4-8b34-25dda8061b07',
                             role_id='9db782df-6704-458a-8bcd-426103e7808d', permission_id='3d8012ca-19d1-454e-86e1-de22a1cc8db1')

        model.objects.create(id='b91424fe-49f6-4d33-8ede-ed65ef1be7fe',
                             role_id='9db782df-6704-458a-8bcd-426103e7808d', permission_id='443c5932-2bde-484e-ac0a-b1c4923b6894')

        model.objects.create(id='2f327311-ed94-4c10-a345-cb369adce987',
                             role_id='9db782df-6704-458a-8bcd-426103e7808d', permission_id='4da86518-425a-4ece-84b3-fcfd50775322')

        model.objects.create(id='da9fb84f-3977-427e-ac76-f4447e73be88',
                             role_id='9db782df-6704-458a-8bcd-426103e7808d', permission_id='4fa783ad-527f-4d60-9167-19a6733c8eb9')

        model.objects.create(id='6316f999-6271-491d-b814-ce41f9bd9b32',
                             role_id='9db782df-6704-458a-8bcd-426103e7808d', permission_id='5acfd868-89ea-48d0-911b-ba4e8ea1624c')

        model.objects.create(id='42e556b1-ef1d-4774-8242-d15e143fe024',
                             role_id='9db782df-6704-458a-8bcd-426103e7808d', permission_id='5ffb4666-7920-4620-99e9-ba5a76c4e990')

        model.objects.create(id='b3295529-463b-424b-a761-6eb061e507bf',
                             role_id='9db782df-6704-458a-8bcd-426103e7808d', permission_id='658e2c1a-b590-42c7-9513-7804f8c51396')

        model.objects.create(id='85f873c4-7a53-4571-bbfc-b9ffbe39230f',
                             role_id='9db782df-6704-458a-8bcd-426103e7808d', permission_id='75a54674-638d-4ef6-ab48-c26f0f1c3fdf')

        model.objects.create(id='16cb105c-2451-4692-a86c-8786301d8cd6',
                             role_id='9db782df-6704-458a-8bcd-426103e7808d', permission_id='7aa09a7f-68a6-4ca6-b6a4-41a94cdb9095')

        model.objects.create(id='dc1e5b1a-71e4-4ff9-a167-93a5db0ff41a',
                             role_id='9db782df-6704-458a-8bcd-426103e7808d', permission_id='815a268a-c14d-4455-bba2-625ce707a6e2')

        model.objects.create(id='2906b3e9-824e-4bf2-853c-5632abb88b48',
                             role_id='9db782df-6704-458a-8bcd-426103e7808d', permission_id='8d517df5-4784-4b16-8269-e138236c7d26')

        model.objects.create(id='9efeacd3-8b17-4fe9-a2dd-d9ffc87544d7',
                             role_id='9db782df-6704-458a-8bcd-426103e7808d', permission_id='9625b6d8-ae36-4287-8e39-4596d6ae96ad')

        model.objects.create(id='7498e025-71f0-4162-9758-a5bbb8bccb93',
                             role_id='9db782df-6704-458a-8bcd-426103e7808d', permission_id='9c5e2a75-203b-4b14-9c9d-781b27464375')

        model.objects.create(id='923ef83c-6199-4709-a0f6-fae51c1fa8ed',
                             role_id='9db782df-6704-458a-8bcd-426103e7808d', permission_id='a674ddf7-083f-41f1-a913-5bf08fe2578b')

        model.objects.create(id='f2a2accf-8b54-4174-a62a-b8273c4bf3ec',
                             role_id='9db782df-6704-458a-8bcd-426103e7808d', permission_id='ada774f6-dc22-492b-9282-fa56af44549e')

        model.objects.create(id='c7469285-40b3-4141-9fa3-6e34561e9567',
                             role_id='9db782df-6704-458a-8bcd-426103e7808d', permission_id='b8cbf78e-9169-4f01-9c66-90bead34420d')

        model.objects.create(id='ef662121-d9a4-4953-ab4f-e0c5e59305e2',
                             role_id='9db782df-6704-458a-8bcd-426103e7808d', permission_id='c221027a-034b-4ea9-9cf4-27a8b1bae1d0')

        model.objects.create(id='b6d4b39f-4584-4447-ae4d-e90d1c13a364',
                             role_id='9db782df-6704-458a-8bcd-426103e7808d', permission_id='ccd87130-76b2-4b4a-b5cb-4c128b2adff0')

        model.objects.create(id='706d5504-6e0b-4b38-84f4-e3e955bb2542',
                             role_id='9db782df-6704-458a-8bcd-426103e7808d', permission_id='d54df0de-85cd-4d92-8f8b-97d5aade1f8d')

        model.objects.create(id='733b7248-ca16-460f-be42-3898ca5da21f',
                             role_id='9db782df-6704-458a-8bcd-426103e7808d', permission_id='db26e13d-a0e1-448e-b75c-7d444d4cc016')

        model.objects.create(id='6ed8a1be-19ac-4567-92a2-97955ce912b8',
                             role_id='9db782df-6704-458a-8bcd-426103e7808d', permission_id='fc40143f-c617-49cf-b83d-a8c3b0c7f1aa')

    dependencies = [
        ('authentication', '0005_auto_20220819_1957'),
    ]

    operations = [
        migrations.RunPython(load_initial_data),
    ]
