from .permission.index import *
from .role.index import *
from .role_permission.index import *
from .user.index import *
from .user_role.index import *
from .permission.index import *
from .role.index import *
from .role_permission.index import *
from .user.index import *
from .user_role.index import *